# Generated by Django 3.0.7 on 2022-04-13 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='car_id',
            new_name='cars_id',
        ),
    ]
