# Generated by Django 3.0.7 on 2022-04-13 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20220413_2140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='cars_id',
            new_name='car_id',
        ),
    ]
